//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Hatchet.rc
//
#define IDD_Hatchet_DIALOG              102
#define IDD_MAIN                        102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDB_BORDER                      129
#define IDB_TAB                         130
#define IDB_CAPTION                     131
#define IDB_CLOSEBTN                    132
#define IDB_MAXBTN                      133
#define IDB_MINBTN                      134
#define IDI_CMD                         135
#define IDI_DATA                        136
#define IDI_DIR                         137
#define IDI_FILESAVE                    138
#define IDI_TYPE                        139
#define IDI_ASP                         140
#define IDI_ASPX                        141
#define IDI_PHP                         143
#define IDR_MENU1                       144
#define IDD_SETPSITE                    145
#define IDD_FILE                        146
#define IDD_CMD                         147
#define IDD_DATA                        148
#define IDD_FILESAVE                    149
#define IDD_WGET                        150
#define IDI_DRIVE                       151
#define IDI_TABLE                       152
#define IDI_COLUMNS                     153
#define IDD_SETPDATA                    154
#define IDD_PROXY                       155
#define IDI_PROXY                       156
#define IDD_EVALCODE                    157
#define IDI_JSP                         159
#define IDB_TRAYBTN                     160
#define IDD_REGISTRY                    161
#define IDI_REGISTRY                    162
#define IDD_BROWSE                      163
#define IDI_BROWSE                      165
#define IDC_SITELIST                    1000
#define IDC_TYPETREE                    1001
#define IDC_EDIT_FIND                   1002
#define IDC_EDIT_SETPSITE_URL           1003
#define IDC_EDIT_SETPSITE_PASS          1004
#define IDC_EDIT_SETPSITE_CONFIG        1005
#define IDC_COMBO_NTYPE                 1006
#define IDC_COMBO_NSCRIPT               1007
#define IDC_COMBO_NCODEPAGE             1008
#define IDC_COMBO_FILEPATH              1009
#define IDC_READFILES                   1010
#define IDC_FILE_TREE                   1011
#define IDC_FILE_LIST                   1012
#define IDC_EDIT_FILE_SUBITEM           1013
#define IDC_CMD                         1014
#define IDC_EDIT_FILEPATH               1015
#define IDC_EDIT_FILECONTENT            1016
#define IDC_FILESAVE_EDIT_FIND          1017
#define IDC_SAVE                        1018
#define IDC_GET_CONTENT                 1019
#define IDC_BUTTON_EXECSQL              1020
#define IDC_DATA_TREE                   1021
#define IDC_DATA_LIST                   1022
#define IDC_COMBO_SQL                   1023
#define IDC_COMBO_DATAS                 1024
#define IDC_EDIT_DATA_SUBITEM           1025
#define IDC_DATA_CONFIG                 1026
#define IDC_EDIT_WGET_URL               1027
#define IDC_EDIT_WGET_PATH              1028
#define IDC_ONWGET                      1029
#define IDC_EDIT_PROXY_PORT             1030
#define IDC_STATIC_PROXY_1              1031
#define IDC_BUTTON_PROXY_START          1032
#define IDC_PROXY_LIST                  1033
#define IDC_BUTTON_PROXY_STOP           1034
#define IDC_EVALCODE_CODE               1035
#define ID_EVALCODE_OK                  1036
#define IDC_BUTTON1                     1036
#define IDC_UPPERSTORY                  1036
#define ID_EVALCODE_CANCEL              1037
#define IDC_CHECK_JOIN                  1037
#define IDC_EVALCODE_CONTENT            1038
#define IDC_COMBO1                      1038
#define IDC_COMBO_JOIN                  1038
#define IDC_EVALCODE_IMPORT             1039
#define IDC_EVALCODE_EXPORT             1040
#define IDC_COMBO_DEMO                  1041
#define IDC_DATA_SETP                   1042
#define IDC_REGISTRY_COMBO              1043
#define IDC_REGISTRY_BUTTON             1044
#define IDC_REGISTRY_TREE               1045
#define IDC_REGISTRY_LIST               1046
#define IDC_REGISTRY_CMD                1047
#define IDC_REGISTRY_RADIO_CMD          1048
#define IDC_REGISTRY_RADIO_WSCRIPT      1049
#define IDC_EXPLORER1                   1050
#define IDC_COMBO_ADDRESS               1051
#define IDC_BROWSE_OK                   1052
#define IDC_BROWSE_STOP                 1053
#define ID_Hatchet_ADD                  32771
#define ID_Hatchet_EDIT                 32772
#define ID_Hatchet_DEL                  32773
#define ID_MAIN_FILE                    32774
#define ID_MAIN_CMD                     32775
#define ID_MAIN_DATA                    32776
#define ID_MAIN_ADD                     32777
#define ID_MAIN_EDIT                    32778
#define ID_MAIN_DELETE                  32779
#define ID_MAIN_FIND                    32780
#define ID_MAIN2_ADD                    32781
#define ID_MAIN2_FIND                   32782
#define ID_DATA_GETCOUNT                32783
#define ID_DATA_SETCLIPBOARD            32784
#define ID_DATA_EXPORTHTML              32785
#define ID_FILE_REFRESH                 32786
#define ID_FILE_CLEARCACHE              32787
#define ID_FILE_UPLOADFILE              32788
#define ID_FILE_DOWNLOADFILE            32789
#define ID_FILE_WGET                    32790
#define ID_FILE_DELETEFILES             32791
#define ID_FILE_RENAME                  32792
#define ID_FILE_CHANGETIME              32793
#define ID_FILE_NEWDIRECTORY            32794
#define ID_FILE_NEWFILE                 32795
#define ID_MAIN_PROXY                   32796
#define ID_FILE_EDITFILE                32797
#define ID_MAIN_EVALCODE                32798
#define ID_MAIN_UPDATEINI               32799
#define ID_MAIN2_UPDATEINI              32800
#define ID_DATALIST_EXPORTTXT           32801
#define ID_DATAT_EXPORTTEXT             32802
#define ID_DATA_EXPORTTEXT              32803
#define ID_FILE_COPY                    32804
#define ID_FILE_CUT                     32805
#define ID_FILE_PASTE                   32806
#define ID_MAIN_REGISTRY                32807
#define ID_REGISTRY_REFRESH             32808
#define ID_REGISTRY_CLEARTHECACHESITE   32809
#define ID_DATATREE_QUERY20LINES        32810
#define ID_MAIN_                        32811
#define ID_MAIN_COPYURL                 32812
#define ID_MAIN_BROWSE                  32813
#define ID_DATATREE_DROPTABLE           32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
